services:
  article-db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${TYPOO_ARTICLE_DB_NAME}
      POSTGRES_USER: ${TYPOO_ARTICLE_DB_USERNAME}
      POSTGRES_PASSWORD: ${TYPOO_ARTICLE_DB_PASSWORD}
    command: [ "postgres", "-c", "max_connections=1000" ]
    volumes:
      - typoo_article_db_data:/var/lib/postgresql/data
    networks:
      - typoo_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TYPOO_ARTICLE_DB_USERNAME} -d ${TYPOO_ARTICLE_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    networks:
      - typoo_network
    command: "consul agent -dev -client=0.0.0.0"

  config-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: config-server
    environment:
      SPRING_APPLICATION_NAME: config-server
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
    ports:
      - "8888:8888"
    volumes:
      - ./services/config-server/config:/services/config-server/config
    secrets:
      - config-server_env_file
    depends_on:
      - consul
    networks:
      - typoo_network
    restart: unless-stopped

  gateway-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: gateway-server
    environment:
      SPRING_APPLICATION_NAME: gateway-server
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
    ports:
      - "8080:8080"
    secrets:
      - gateway-server_env_file
    depends_on:
      - consul
      - config-server
    networks:
      - typoo_network
    restart: unless-stopped

  article-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: article-service
    environment:
      SPRING_APPLICATION_NAME: article-service
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
    secrets:
      - article-service_env_file
    #    ports:
    #      - "8081:8081"
    depends_on:
      article-db:
        condition: service_healthy
      config-server:
        condition: service_started
      gateway-server:
        condition: service_started
    networks:
      - typoo_network
    restart: unless-stopped

secrets:
  config-server_env_file:
    file: ./services/config-server/.env.${SPRING_PROFILES_ACTIVE:-docker}
  gateway-server_env_file:
    file: ./services/gateway-server/.env.${SPRING_PROFILES_ACTIVE:-docker}
  article-service_env_file:
    file: ./services/article-service/.env.${SPRING_PROFILES_ACTIVE:-docker}

volumes:
  typoo_article_db_data:

networks:
  typoo_network:
    driver: bridge