services:
  typoo-db:
    image: postgres:17
    container_name: typoo_db_container
    env_file:
      - .env
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: [ "postgres", "-c", "max_connections=1000" ]
    volumes:
      - typoo_db_data:/var/lib/postgresql/data
    networks:
      - typoo_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  article-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: article-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      typoo-db:
        condition: service_healthy
    networks:
      - typoo_network
    restart: unless-stopped

volumes:
  typoo_db_data:

networks:
  typoo_network:
    driver: bridge