management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.prometheus.metrics.export.enabled=true
#
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-critical-timeout=1m
#
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
#
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=60s
#
dotenv.enabled=true
dotenv.base-path=services/{service}
dotenv.filename=.env.{profile}
dotenv.secrets-path=/run/secrets
dotenv.override-existing=false