spring.datasource.url=${TYPOO_ARTICLE_DB_URL}
spring.datasource.username=${TYPOO_ARTICLE_DB_USERNAME}
spring.datasource.password=${TYPOO_ARTICLE_DB_PASSWORD}
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
#
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/liquibase/changelog-master.yml