server.port=${TYPOO_ARTICLE_PORT:8081}
#
spring.datasource.url=${TYPOO_ARTICLE_DB_URL}
spring.datasource.username=${TYPOO_ARTICLE_DB_USERNAME}
spring.datasource.password=${TYPOO_ARTICLE_DB_PASSWORD}
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#
spring.liquibase.change-log=classpath:db/liquibase/changelog-master.yml
spring.liquibase.enabled=true
#
logging.level.org.springframework=INFO
logging.level.com.agorohov=DEBUG
#
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
#
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
#
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-critical-timeout=1m