spring.cloud.gateway.server.webflux.routes[0].id=article-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://article-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/article/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
#
logging.level.org.springframework.cloud.gateway=DEBUG