global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'gateway-server:8080' ]
  - job_name: 'article-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'article-service:8081' ]

rule_files:
  - "alerts.yml"