server.port=8888
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.profiles.include=native
spring.application.name=${SPRING_APPLICATION_NAME:config-server}
spring.cloud.config.server.git.enabled=false
spring.cloud.config.server.native.enabled=true
spring.cloud.config.server.native.search-locations=file:./services/config-server/config
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
# DotenvLoader
dotenv.enabled=true
dotenv.base-path=services/{service}
dotenv.filename=.env.{profile}
dotenv.secrets-path=/run/secrets
dotenv.override-existing=false