# Server
server.port=8080
# DB
spring.datasource.url=jdbc:postgresql://typoo-db:5432/typoo_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=typoo_article_user
spring.datasource.password=typoo_article_pass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update