server.port=8081
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=article-service
spring.config.import=optional:configserver:http://localhost:8888
#
spring.datasource.url=${TYPOO_ARTICLE_DB_URL}
spring.datasource.username=${TYPOO_ARTICLE_DB_USERNAME}
spring.datasource.password=${TYPOO_ARTICLE_DB_PASSWORD}
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
spring.jpa.hibernate.ddl-auto=${TYPOO_ARTICLE_DDL_AUTO:validate}
spring.jpa.show-sql=${TYPOO_ARTICLE_SHOW_SQL:false}
#
spring.jpa.properties.hibernate.format_sql=${TYPOO_ARTICLE_FORMAT_SQL:false}
spring.jpa.properties.hibernate.use_sql_comments=${TYPOO_ARTICLE_USE_SQL_COMMENTS:false}
#
spring.liquibase.change-log=classpath:db/liquibase/changelog-master.yml
spring.liquibase.enabled=${TYPOO_ARTICLE_LIQUIBASE_ENABLED:true}
#
logging.level.org.springframework=INFO
logging.level.com.agorohov=DEBUG